<?php

return [
	'SITE_TITLE' => $_ENV['SITE_TITLE'],
	'BASE_URL' => $_ENV['BASE_URL'],
	'BASE_PATH' => $_ENV['BASE_PATH'],
	'ROUTER_DEBUG' => $_ENV['ROUTER_DEBUG'],
	'DISPLAY_ERRORS' =>$_ENV['DISPLAY_ERRORS'],
	'DISPLAY_STARTUP_ERRORS' =>$_ENV['DISPLAY_STARTUP_ERRORS'],
	'ERROR_REPORTING' =>$_ENV['ERROR_REPORTING']
];